version: 3
projects:
  - dir: .
    workflow: use-prod-vars
    autoplan:
      enabled: true
      when_modified:
        - "*.tf"
        - "prod.tfvars"

workflows:
  use-prod-vars:
    plan:
      steps:
        - run: terraform plan -var-file="prod.tfvars"
    apply:
      steps:
        - run: terraform apply -var-file="prod.tfvars"
