version: 3
projects:
  - dir: .
    workflow: 
    autoplan:
      enabled: true
      when_modified:
        - "*.tf"
        - "prod.tfvars"

workflows:
  use-prod-vars:
    plan:
      steps:
        - init
        - plan:
            extra_args: ["-var-file=prod.tfvars"]
    apply:
      steps:
        - apply:
            extra_args: ["-var-file=prod.tfvars"]
